// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Mn.NewsCms.Web.Areas.Dashboard.Controllers
{
    public partial class UpdaterController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UpdaterController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UpdaterController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateFeed()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateFeed);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Start()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Start);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Durations_Read()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Durations_Read);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UpdaterController Actions { get { return MVC.Dashboard.Updater; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Dashboard";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Updater";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Updater";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Duration = "Duration";
            public readonly string UpdateFeed = "UpdateFeed";
            public readonly string Start = "Start";
            public readonly string Optimize = "Optimize";
            public readonly string FeedsCheck = "FeedsCheck";
            public readonly string Durations_Read = "Durations_Read";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Duration = "Duration";
            public const string UpdateFeed = "UpdateFeed";
            public const string Start = "Start";
            public const string Optimize = "Optimize";
            public const string FeedsCheck = "FeedsCheck";
            public const string Durations_Read = "Durations_Read";
        }


        static readonly ActionParamsClass_UpdateFeed s_params_UpdateFeed = new ActionParamsClass_UpdateFeed();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateFeed UpdateFeedParams { get { return s_params_UpdateFeed; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateFeed
        {
            public readonly string feedId = "feedId";
        }
        static readonly ActionParamsClass_Start s_params_Start = new ActionParamsClass_Start();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Start StartParams { get { return s_params_Start; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Start
        {
            public readonly string param = "param";
        }
        static readonly ActionParamsClass_Durations_Read s_params_Durations_Read = new ActionParamsClass_Durations_Read();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Durations_Read Durations_ReadParams { get { return s_params_Durations_Read; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Durations_Read
        {
            public readonly string request = "request";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Duration = "Duration";
                public readonly string FeedsCheck = "FeedsCheck";
                public readonly string Index = "Index";
                public readonly string Start = "Start";
            }
            public readonly string Duration = "~/Areas/Dashboard/Views/Updater/Duration.cshtml";
            public readonly string FeedsCheck = "~/Areas/Dashboard/Views/Updater/FeedsCheck.cshtml";
            public readonly string Index = "~/Areas/Dashboard/Views/Updater/Index.cshtml";
            public readonly string Start = "~/Areas/Dashboard/Views/Updater/Start.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UpdaterController : Mn.NewsCms.Web.Areas.Dashboard.Controllers.UpdaterController
    {
        public T4MVC_UpdaterController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DurationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Duration()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Duration);
            DurationOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UpdateFeedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int feedId);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateFeed(int feedId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateFeed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "feedId", feedId);
            UpdateFeedOverride(callInfo, feedId);
            return callInfo;
        }

        [NonAction]
        partial void StartOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string param);

        [NonAction]
        public override System.Web.Mvc.ActionResult Start(string param)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Start);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "param", param);
            StartOverride(callInfo, param);
            return callInfo;
        }

        [NonAction]
        partial void OptimizeOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult Optimize()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Optimize);
            OptimizeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FeedsCheckOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult FeedsCheck()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FeedsCheck);
            FeedsCheckOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Durations_ReadOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Kendo.Mvc.UI.DataSourceRequest request);

        [NonAction]
        public override System.Web.Mvc.JsonResult Durations_Read(Kendo.Mvc.UI.DataSourceRequest request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Durations_Read);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            Durations_ReadOverride(callInfo, request);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
