// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Mn.NewsCms.Web.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FeedItems()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FeedItems);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Script()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Script);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Review = "Review";
            public readonly string FeedItems = "FeedItems";
            public readonly string About = "About";
            public readonly string Contact = "Contact";
            public readonly string ads = "ads";
            public readonly string techs = "techs";
            public readonly string Script = "Script";
            public readonly string Video = "Video";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Review = "Review";
            public const string FeedItems = "FeedItems";
            public const string About = "About";
            public const string Contact = "Contact";
            public const string ads = "ads";
            public const string techs = "techs";
            public const string Script = "Script";
            public const string Video = "Video";
        }


        static readonly ActionParamsClass_FeedItems s_params_FeedItems = new ActionParamsClass_FeedItems();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FeedItems FeedItemsParams { get { return s_params_FeedItems; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FeedItems
        {
            public readonly string Content = "Content";
            public readonly string PageIndex = "PageIndex";
            public readonly string type = "type";
        }
        static readonly ActionParamsClass_Script s_params_Script = new ActionParamsClass_Script();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Script ScriptParams { get { return s_params_Script; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Script
        {
            public readonly string src = "src";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _IndexPosts = "_IndexPosts";
                public readonly string _ItemsSlider = "_ItemsSlider";
                public readonly string _MoreItems = "_MoreItems";
                public readonly string About = "About";
                public readonly string Ads = "Ads";
                public readonly string Contact = "Contact";
                public readonly string Index_Sekuzan = "Index.Sekuzan";
                public readonly string Index_Tazeyab___Copy = "Index.Tazeyab - Copy";
                public readonly string Index_Tazeyab = "Index.Tazeyab";
                public readonly string IndexItem = "IndexItem";
                public readonly string IndexItemByTag = "IndexItemByTag";
                public readonly string IndexItems = "IndexItems";
                public readonly string Review = "Review";
                public readonly string techs = "techs";
                public readonly string Today = "Today";
                public readonly string Video = "Video";
            }
            public readonly string _IndexPosts = "~/Views/Home/_IndexPosts.cshtml";
            public readonly string _ItemsSlider = "~/Views/Home/_ItemsSlider.cshtml";
            public readonly string _MoreItems = "~/Views/Home/_MoreItems.cshtml";
            public readonly string About = "~/Views/Home/About.cshtml";
            public readonly string Ads = "~/Views/Home/Ads.cshtml";
            public readonly string Contact = "~/Views/Home/Contact.cshtml";
            public readonly string Index_Sekuzan = "~/Views/Home/Index.Sekuzan.cshtml";
            public readonly string Index_Tazeyab___Copy = "~/Views/Home/Index.Tazeyab - Copy.cshtml";
            public readonly string Index_Tazeyab = "~/Views/Home/Index.Tazeyab.cshtml";
            public readonly string IndexItem = "~/Views/Home/IndexItem.cshtml";
            public readonly string IndexItemByTag = "~/Views/Home/IndexItemByTag.cshtml";
            public readonly string IndexItems = "~/Views/Home/IndexItems.cshtml";
            public readonly string Review = "~/Views/Home/Review.cshtml";
            public readonly string techs = "~/Views/Home/techs.cshtml";
            public readonly string Today = "~/Views/Home/Today.cshtml";
            public readonly string Video = "~/Views/Home/Video.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : Mn.NewsCms.Web.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ReviewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Review()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Review);
            ReviewOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FeedItemsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string Content, int PageIndex, string type);

        [NonAction]
        public override System.Web.Mvc.ActionResult FeedItems(string Content, int PageIndex, string type)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FeedItems);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Content", Content);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "PageIndex", PageIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            FeedItemsOverride(callInfo, Content, PageIndex, type);
            return callInfo;
        }

        [NonAction]
        partial void AboutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult About()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.About);
            AboutOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ContactOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Contact()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Contact);
            ContactOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void adsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ads()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ads);
            adsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void techsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult techs()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.techs);
            techsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ScriptOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string src);

        [NonAction]
        public override System.Web.Mvc.ActionResult Script(string src)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Script);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "src", src);
            ScriptOverride(callInfo, src);
            return callInfo;
        }

        [NonAction]
        partial void VideoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Video()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Video);
            VideoOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
