// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Tazeyab.Web.Controllers
{
    public partial class SharedController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SharedController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SharedController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SharedController Actions { get { return MVC.Shared; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Shared";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Shared";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string AnalysisScripts = "AnalysisScripts";
            public readonly string ShareInSocialScripts = "ShareInSocialScripts";
            public readonly string TopMenu = "TopMenu";
            public readonly string TopMenuMember = "TopMenuMember";
            public readonly string HeaderMenu = "HeaderMenu";
            public readonly string Footer = "Footer";
            public readonly string FooterMenu = "FooterMenu";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string AnalysisScripts = "AnalysisScripts";
            public const string ShareInSocialScripts = "ShareInSocialScripts";
            public const string TopMenu = "TopMenu";
            public const string TopMenuMember = "TopMenuMember";
            public const string HeaderMenu = "HeaderMenu";
            public const string Footer = "Footer";
            public const string FooterMenu = "FooterMenu";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _FeedItems_Sekuzan = "_FeedItems.Sekuzan";
                public readonly string _FeedItems_Tazeyab = "_FeedItems.Tazeyab";
                public readonly string _FeedItemsRemote = "_FeedItemsRemote";
                public readonly string _Items = "_Items";
                public readonly string _Layout_Sekuzan = "_Layout.Sekuzan";
                public readonly string _Layout_Tazeyab = "_Layout.Tazeyab";
                public readonly string _LayoutFeedItems_Sekuzan = "_LayoutFeedItems.Sekuzan";
                public readonly string _LayoutFeedItems_Tazeyab = "_LayoutFeedItems.Tazeyab";
                public readonly string _LayoutStandard_Sekuzan = "_LayoutStandard.Sekuzan";
                public readonly string _LayoutStandard_Tazeyab = "_LayoutStandard.Tazeyab";
                public readonly string _LogOnPartial = "_LogOnPartial";
                public readonly string _Script = "_Script";
                public readonly string _SearchBox = "_SearchBox";
                public readonly string _Sponser = "_Sponser";
                public readonly string _UserIndex = "_UserIndex";
                public readonly string BaseLayout_Sekuzan = "BaseLayout.Sekuzan";
                public readonly string BaseLayout_Tazeyab = "BaseLayout.Tazeyab";
            }
            public readonly string _FeedItems_Sekuzan = "~/Views/Shared/_FeedItems.Sekuzan.cshtml";
            public readonly string _FeedItems_Tazeyab = "~/Views/Shared/_FeedItems.Tazeyab.cshtml";
            public readonly string _FeedItemsRemote = "~/Views/Shared/_FeedItemsRemote.cshtml";
            public readonly string _Items = "~/Views/Shared/_Items.cshtml";
            public readonly string _Layout_Sekuzan = "~/Views/Shared/_Layout.Sekuzan.cshtml";
            public readonly string _Layout_Tazeyab = "~/Views/Shared/_Layout.Tazeyab.cshtml";
            public readonly string _LayoutFeedItems_Sekuzan = "~/Views/Shared/_LayoutFeedItems.Sekuzan.cshtml";
            public readonly string _LayoutFeedItems_Tazeyab = "~/Views/Shared/_LayoutFeedItems.Tazeyab.cshtml";
            public readonly string _LayoutStandard_Sekuzan = "~/Views/Shared/_LayoutStandard.Sekuzan.cshtml";
            public readonly string _LayoutStandard_Tazeyab = "~/Views/Shared/_LayoutStandard.Tazeyab.cshtml";
            public readonly string _LogOnPartial = "~/Views/Shared/_LogOnPartial.cshtml";
            public readonly string _Script = "~/Views/Shared/_Script.cshtml";
            public readonly string _SearchBox = "~/Views/Shared/_SearchBox.cshtml";
            public readonly string _Sponser = "~/Views/Shared/_Sponser.cshtml";
            public readonly string _UserIndex = "~/Views/Shared/_UserIndex.cshtml";
            public readonly string BaseLayout_Sekuzan = "~/Views/Shared/BaseLayout.Sekuzan.cshtml";
            public readonly string BaseLayout_Tazeyab = "~/Views/Shared/BaseLayout.Tazeyab.cshtml";
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string _Flag = "_Flag";
                public readonly string _PageRank = "_PageRank";
                public readonly string _ShowContentType = "_ShowContentType";
                public readonly string _TagDropDown = "_TagDropDown";
            }
            static readonly _NavigationClass s_Navigation = new _NavigationClass();
            public _NavigationClass Navigation { get { return s_Navigation; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _NavigationClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Footer = "_Footer";
                    public readonly string _FooterMenu = "_FooterMenu";
                    public readonly string _HeaderMenu_Sekuzan = "_HeaderMenu.Sekuzan";
                    public readonly string _SocialMenu = "_SocialMenu";
                    public readonly string _TopMenu_Sekuzan = "_TopMenu.Sekuzan";
                    public readonly string _TopMenu_Tazeyab = "_TopMenu.Tazeyab";
                    public readonly string _TopMenuMember_Tazeyab = "_TopMenuMember.Tazeyab";
                }
                public readonly string _Footer = "~/Views/Shared/Navigation/_Footer.cshtml";
                public readonly string _FooterMenu = "~/Views/Shared/Navigation/_FooterMenu.cshtml";
                public readonly string _HeaderMenu_Sekuzan = "~/Views/Shared/Navigation/_HeaderMenu.Sekuzan.cshtml";
                public readonly string _SocialMenu = "~/Views/Shared/Navigation/_SocialMenu.cshtml";
                public readonly string _TopMenu_Sekuzan = "~/Views/Shared/Navigation/_TopMenu.Sekuzan.cshtml";
                public readonly string _TopMenu_Tazeyab = "~/Views/Shared/Navigation/_TopMenu.Tazeyab.cshtml";
                public readonly string _TopMenuMember_Tazeyab = "~/Views/Shared/Navigation/_TopMenuMember.Tazeyab.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SharedController : Tazeyab.Web.Controllers.SharedController
    {
        public T4MVC_SharedController() : base(Dummy.Instance) { }

        [NonAction]
        partial void AnalysisScriptsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AnalysisScripts()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AnalysisScripts);
            AnalysisScriptsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ShareInSocialScriptsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShareInSocialScripts()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShareInSocialScripts);
            ShareInSocialScriptsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TopMenuOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TopMenu()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopMenu);
            TopMenuOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TopMenuMemberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TopMenuMember()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopMenuMember);
            TopMenuMemberOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void HeaderMenuOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult HeaderMenu()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HeaderMenu);
            HeaderMenuOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FooterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Footer()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Footer);
            FooterOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FooterMenuOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult FooterMenu()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FooterMenu);
            FooterMenuOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
