// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Tazeyab.Web.Controllers
{
    public partial class ToolboxController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ToolboxController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ToolboxController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult script()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.script);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Demo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Demo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddEditFeed()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddEditFeed);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetSite()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetSite);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetFeeds()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetFeeds);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetCats()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCats);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ToolboxController Actions { get { return MVC.Toolbox; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Toolbox";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Toolbox";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string script = "script";
            public readonly string Demo = "Demo";
            public readonly string AddWebSite = "AddWebSite";
            public readonly string AddEditFeed = "AddEditFeed";
            public readonly string GetSite = "GetSite";
            public readonly string GetFeeds = "GetFeeds";
            public readonly string GetCats = "GetCats";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string script = "script";
            public const string Demo = "Demo";
            public const string AddWebSite = "AddWebSite";
            public const string AddEditFeed = "AddEditFeed";
            public const string GetSite = "GetSite";
            public const string GetFeeds = "GetFeeds";
            public const string GetCats = "GetCats";
        }


        static readonly ActionParamsClass_script s_params_script = new ActionParamsClass_script();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_script scriptParams { get { return s_params_script; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_script
        {
            public readonly string src = "src";
        }
        static readonly ActionParamsClass_Demo s_params_Demo = new ActionParamsClass_Demo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Demo DemoParams { get { return s_params_Demo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Demo
        {
            public readonly string Content = "Content";
            public readonly string PagePath = "PagePath";
            public readonly string Title = "Title";
        }
        static readonly ActionParamsClass_AddWebSite s_params_AddWebSite = new ActionParamsClass_AddWebSite();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddWebSite AddWebSiteParams { get { return s_params_AddWebSite; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddWebSite
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddEditFeed s_params_AddEditFeed = new ActionParamsClass_AddEditFeed();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddEditFeed AddEditFeedParams { get { return s_params_AddEditFeed; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddEditFeed
        {
            public readonly string siteId = "siteId";
            public readonly string request = "request";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetSite s_params_GetSite = new ActionParamsClass_GetSite();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetSite GetSiteParams { get { return s_params_GetSite; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetSite
        {
            public readonly string url = "url";
        }
        static readonly ActionParamsClass_GetFeeds s_params_GetFeeds = new ActionParamsClass_GetFeeds();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetFeeds GetFeedsParams { get { return s_params_GetFeeds; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetFeeds
        {
            public readonly string siteId = "siteId";
        }
        static readonly ActionParamsClass_GetCats s_params_GetCats = new ActionParamsClass_GetCats();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCats GetCatsParams { get { return s_params_GetCats; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCats
        {
            public readonly string viewMode = "viewMode";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AddFeedsToSite = "AddFeedsToSite";
                public readonly string AddWebSite = "AddWebSite";
                public readonly string Demo = "Demo";
                public readonly string Index = "Index";
            }
            public readonly string AddFeedsToSite = "~/Views/Toolbox/AddFeedsToSite.cshtml";
            public readonly string AddWebSite = "~/Views/Toolbox/AddWebSite.cshtml";
            public readonly string Demo = "~/Views/Toolbox/Demo.cshtml";
            public readonly string Index = "~/Views/Toolbox/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ToolboxController : Tazeyab.Web.Controllers.ToolboxController
    {
        public T4MVC_ToolboxController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void scriptOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string src);

        [NonAction]
        public override System.Web.Mvc.ActionResult script(string src)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.script);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "src", src);
            scriptOverride(callInfo, src);
            return callInfo;
        }

        [NonAction]
        partial void DemoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string Content, string PagePath, string Title);

        [NonAction]
        public override System.Web.Mvc.ActionResult Demo(string Content, string PagePath, string Title)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Demo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Content", Content);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "PagePath", PagePath);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Title", Title);
            DemoOverride(callInfo, Content, PagePath, Title);
            return callInfo;
        }

        [NonAction]
        partial void AddWebSiteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddWebSite()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddWebSite);
            AddWebSiteOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AddWebSiteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Tazeyab.Web.Models.AddWebSiteViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddWebSite(Tazeyab.Web.Models.AddWebSiteViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddWebSite);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddWebSiteOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void AddEditFeedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long siteId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddEditFeed(long siteId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddEditFeed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "siteId", siteId);
            AddEditFeedOverride(callInfo, siteId);
            return callInfo;
        }

        [NonAction]
        partial void AddEditFeedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, Tazeyab.Web.Models.FeedViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddEditFeed(Kendo.Mvc.UI.DataSourceRequest request, Tazeyab.Web.Models.FeedViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddEditFeed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddEditFeedOverride(callInfo, request, model);
            return callInfo;
        }

        [NonAction]
        partial void GetSiteOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string url);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetSite(string url)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetSite);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "url", url);
            GetSiteOverride(callInfo, url);
            return callInfo;
        }

        [NonAction]
        partial void GetFeedsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int siteId);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetFeeds(int siteId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetFeeds);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "siteId", siteId);
            GetFeedsOverride(callInfo, siteId);
            return callInfo;
        }

        [NonAction]
        partial void GetCatsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Tazeyab.Common.Share.ViewMode viewMode);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCats(Tazeyab.Common.Share.ViewMode viewMode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCats);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewMode", viewMode);
            GetCatsOverride(callInfo, viewMode);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
