// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Mn.NewsCms.Web.Controllers
{
    public partial class UserController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UserController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CatsUsersDeleting()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CatsUsersDeleting);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CatsUsersAdding()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CatsUsersAdding);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SitesUsersDeleting()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SitesUsersDeleting);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SitesUsersAdding()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SitesUsersAdding);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TagsUsersDeleting()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TagsUsersDeleting);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TagsUsersAdding()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TagsUsersAdding);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserController Actions { get { return MVC.User; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "User";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "User";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string CatsUsersDeleting = "CatsUsersDeleting";
            public readonly string CatsUsersAdding = "CatsUsersAdding";
            public readonly string SitesUsersDeleting = "SitesUsersDeleting";
            public readonly string SitesUsersAdding = "SitesUsersAdding";
            public readonly string TagsUsersDeleting = "TagsUsersDeleting";
            public readonly string TagsUsersAdding = "TagsUsersAdding";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string CatsUsersDeleting = "CatsUsersDeleting";
            public const string CatsUsersAdding = "CatsUsersAdding";
            public const string SitesUsersDeleting = "SitesUsersDeleting";
            public const string SitesUsersAdding = "SitesUsersAdding";
            public const string TagsUsersDeleting = "TagsUsersDeleting";
            public const string TagsUsersAdding = "TagsUsersAdding";
        }


        static readonly ActionParamsClass_CatsUsersDeleting s_params_CatsUsersDeleting = new ActionParamsClass_CatsUsersDeleting();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CatsUsersDeleting CatsUsersDeletingParams { get { return s_params_CatsUsersDeleting; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CatsUsersDeleting
        {
            public readonly string CatCode = "CatCode";
        }
        static readonly ActionParamsClass_CatsUsersAdding s_params_CatsUsersAdding = new ActionParamsClass_CatsUsersAdding();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CatsUsersAdding CatsUsersAddingParams { get { return s_params_CatsUsersAdding; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CatsUsersAdding
        {
            public readonly string CatCode = "CatCode";
        }
        static readonly ActionParamsClass_SitesUsersDeleting s_params_SitesUsersDeleting = new ActionParamsClass_SitesUsersDeleting();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SitesUsersDeleting SitesUsersDeletingParams { get { return s_params_SitesUsersDeleting; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SitesUsersDeleting
        {
            public readonly string SiteURL = "SiteURL";
        }
        static readonly ActionParamsClass_SitesUsersAdding s_params_SitesUsersAdding = new ActionParamsClass_SitesUsersAdding();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SitesUsersAdding SitesUsersAddingParams { get { return s_params_SitesUsersAdding; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SitesUsersAdding
        {
            public readonly string SiteURL = "SiteURL";
        }
        static readonly ActionParamsClass_TagsUsersDeleting s_params_TagsUsersDeleting = new ActionParamsClass_TagsUsersDeleting();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TagsUsersDeleting TagsUsersDeletingParams { get { return s_params_TagsUsersDeleting; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TagsUsersDeleting
        {
            public readonly string TagContent = "TagContent";
        }
        static readonly ActionParamsClass_TagsUsersAdding s_params_TagsUsersAdding = new ActionParamsClass_TagsUsersAdding();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TagsUsersAdding TagsUsersAddingParams { get { return s_params_TagsUsersAdding; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TagsUsersAdding
        {
            public readonly string TagContent = "TagContent";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index_Sekuzan = "Index.Sekuzan";
                public readonly string Index_Tazeyab = "Index.Tazeyab";
            }
            public readonly string Index_Sekuzan = "~/Views/User/Index.Sekuzan.cshtml";
            public readonly string Index_Tazeyab = "~/Views/User/Index.Tazeyab.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UserController : Mn.NewsCms.Web.Controllers.UserController
    {
        public T4MVC_UserController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CatsUsersDeletingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string CatCode);

        [NonAction]
        public override System.Web.Mvc.ActionResult CatsUsersDeleting(string CatCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CatsUsersDeleting);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "CatCode", CatCode);
            CatsUsersDeletingOverride(callInfo, CatCode);
            return callInfo;
        }

        [NonAction]
        partial void CatsUsersAddingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string CatCode);

        [NonAction]
        public override System.Web.Mvc.ActionResult CatsUsersAdding(string CatCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CatsUsersAdding);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "CatCode", CatCode);
            CatsUsersAddingOverride(callInfo, CatCode);
            return callInfo;
        }

        [NonAction]
        partial void SitesUsersDeletingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string SiteURL);

        [NonAction]
        public override System.Web.Mvc.ActionResult SitesUsersDeleting(string SiteURL)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SitesUsersDeleting);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "SiteURL", SiteURL);
            SitesUsersDeletingOverride(callInfo, SiteURL);
            return callInfo;
        }

        [NonAction]
        partial void SitesUsersAddingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string SiteURL);

        [NonAction]
        public override System.Web.Mvc.ActionResult SitesUsersAdding(string SiteURL)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SitesUsersAdding);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "SiteURL", SiteURL);
            SitesUsersAddingOverride(callInfo, SiteURL);
            return callInfo;
        }

        [NonAction]
        partial void TagsUsersDeletingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string TagContent);

        [NonAction]
        public override System.Web.Mvc.ActionResult TagsUsersDeleting(string TagContent)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TagsUsersDeleting);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "TagContent", TagContent);
            TagsUsersDeletingOverride(callInfo, TagContent);
            return callInfo;
        }

        [NonAction]
        partial void TagsUsersAddingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string TagContent);

        [NonAction]
        public override System.Web.Mvc.ActionResult TagsUsersAdding(string TagContent)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TagsUsersAdding);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "TagContent", TagContent);
            TagsUsersAddingOverride(callInfo, TagContent);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
