// <auto-generated />
namespace Tazeyab.Common.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class mm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mm));
        
        string IMigrationMetadata.Id
        {
            get { return "201502191131379_mm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
