// <auto-generated />
namespace Tazeyab.Common.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class setups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setups));
        
        string IMigrationMetadata.Id
        {
            get { return "201507271405221_setups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
